### ISSUE TITLE
Submit a response to a Survey

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform-client-mzima#599] opened 2023-04-03 12:37 UTC
- [ ] Open Survey
- [ ] Fill in all fields
- [ ] Click Submit to complete response submission process

**Comment by theobadha** [comment] 2023-10-04 03:39
https://linear.app/ushahidi/issue/MZI-210/surveys-submit-a-response-to-a-survey

**Comment by theobadha** [comment] 2023-10-04 10:08
Closing as duplicate of #614

**Closed by theobadha** 2023-10-04 10:08 UTC
Labels: e2e-test-automation, Outreachy 2023
